//This program is pals_lcr-var-start-time.6_false-unreach-call.1.ufo.UNBOUNDED.pals.c







/**********************************************************************

Copyright (c) 2013 Carnegie Mellon University. All Rights Reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following acknowledgments and
disclaimers.

2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

3. The names "Carnegie Mellon University," "SEI" and/or "Software
Engineering Institute" shall not be used to endorse or promote
products derived from this software without prior written
permission. For written permission, please contact
permission@sei.cmu.edu.

4. Products derived from this software may not be called "SEI" nor may
"SEI" appear in their names without prior written permission of
permission@sei.cmu.edu.

5. Redistributions of any form whatsoever must retain the following
acknowledgment:

This material is based upon work funded and supported by the
Department of Defense under Contract No. FA8721-05-C-0003 with
Carnegie Mellon University for the operation of the Software
Engineering Institute, a federally funded research and development
center.

Any opinions, findings and conclusions or recommendations expressed in
this material are those of the author(s) and do not necessarily
reflect the views of the United States Department of Defense.

NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
INSTITUTE MATERIAL IS FURNISHEDON AN "AS-IS" BASIS. CARNEGIE MELLON
UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
TRADEMARK, OR COPYRIGHT INFRINGEMENT.

This material has been approved for public release and unlimited
distribution.

DM-0000575

**********************************************************************/

/* Generated by CIL v. 1.6.0 */
/* print_CIL_Input is true */
#include <stdlib.h>
#include <stdio.h> 
#include <assert.h>
int kappa;
typedef int bool;
#define true 1
#define false 0
typedef char msg_t;
typedef int port_t;
extern void read(port_t p , msg_t m ) ;
extern void write(port_t p , msg_t m ) ;
msg_t nomsg  =    (msg_t )-1;
char r1  ;
port_t p1  ;
char p1_old ;
char p1_new ;
char id1  ;
char st1  ;
msg_t send1  ;
bool mode1  ;
bool alive1  ;
port_t p2  ;
char p2_old ;
char p2_new ;
char id2  ;
char st2  ;
msg_t send2  ;
bool mode2  ;
bool alive2  ;
port_t p3  ;
char p3_old ;
char p3_new ;
char id3  ;
char st3  ;
msg_t send3  ;
bool mode3  ;
bool alive3  ;
port_t p4  ;
char p4_old ;
char p4_new ;
char id4  ;
char st4  ;
msg_t send4  ;
bool mode4  ;
bool alive4  ;
port_t p5  ;
char p5_old ;
char p5_new ;
char id5  ;
char st5  ;
msg_t send5  ;
bool mode5  ;
bool alive5  ;
port_t p6  ;
char p6_old ;
char p6_new ;
char id6  ;
char st6  ;
msg_t send6  ;
bool mode6  ;
bool alive6  ;
void node1(void) 
{ 
  msg_t m1 ;

  {
  m1 = nomsg;
printf("POINT: 1\n");

  if (mode1) {
printf("POINT: 2\n");
printf("POINT: 3\n");

    if (r1 == 255) {
printf("POINT: 4\n");
      r1 = 5;
    }
    r1 = r1 + 1;
    m1 = p6_old;
    p6_old = nomsg;
printf("POINT: 5\n");

    if ((int )m1 != (int )nomsg) {
printf("POINT: 6\n");
printf("POINT: 7\n");

      if (alive1) {
printf("POINT: 8\n");
printf("POINT: 9\n");

        if ((int )m1 > (int )id1) {
printf("POINT: 10\n");
          send1 = m1;
        } else
printf("POINT: 11\n");

        if ((int )m1 == (int )id1) {
printf("POINT: 12\n");
          st1 = (char)1;
        } else {
printf("POINT: 14\n");
          send1 = m1;
        }
      } else {
printf("POINT: 16\n");
        send1 = m1;
      }
    }
    mode1 = (bool)0;
  } else {
printf("POINT: 18\n");
printf("POINT: 19\n");

    if (alive1) {
printf("POINT: 20\n");
      
printf("POINT: 21\n");

    if ((send1 != nomsg) && (p1_new == nomsg)){
printf("POINT: 22\n");
    p1_new = send1;
    }
    else{
    p1_new = p1_new;
    }
      
    } else {
printf("POINT: 24\n");
    
printf("POINT: 25\n");

    if ((int )send1 != (int )id1) {
printf("POINT: 26\n");
    
printf("POINT: 27\n");

    if ((send1 != nomsg) && (p1_new == nomsg)){
printf("POINT: 28\n");
    p1_new = send1;
    }
    else{
    p1_new = p1_new;
    }
    }
    }
    mode1 = (bool)1;
  }
  return;
}
}
void node2(void) 
{ 
  msg_t m2 ;

  {
  m2 = nomsg;
printf("POINT: 29\n");

  if (mode2) {
printf("POINT: 30\n");
    m2 = p1_old;
    p1_old = nomsg;
printf("POINT: 31\n");

    if ((int )m2 != (int )nomsg) {
printf("POINT: 32\n");
printf("POINT: 33\n");

      if (alive2) {
printf("POINT: 34\n");
printf("POINT: 35\n");

        if ((int )m2 > (int )id2) {
printf("POINT: 36\n");
          send2 = m2;
        } else
printf("POINT: 37\n");

        if ((int )m2 == (int )id2) {
printf("POINT: 38\n");
          st2 = (char)1;
        }
      } else {
printf("POINT: 40\n");
        send2 = m2;
      }
    }
    mode2 = (bool)0;
  } else {
printf("POINT: 42\n");
printf("POINT: 43\n");

    if (alive2) {
printf("POINT: 44\n");
      
printf("POINT: 45\n");

          if ((send2 != nomsg) && (p2_new == nomsg)){
printf("POINT: 46\n");
    p2_new = send2;
    }
    else{
    p2_new = p2_new;
    }
    
    
      
    } else{
printf("POINT: 47\n");

    if ((int )send2 != (int )id2) {
printf("POINT: 48\n");
    
printf("POINT: 49\n");

        if ((send2 != nomsg) && (p2_new == nomsg)){
printf("POINT: 50\n");
    p2_new = send2;
    }
    else{
    p2_new = p2_new;
    }
    }
    }
    mode2 = (bool)1;
  }
  return;
}
}
void node3(void) 
{ 
  msg_t m3 ;

  {
  m3 = nomsg;
printf("POINT: 51\n");

  if (mode3) {
printf("POINT: 52\n");
    m3 = p2_old;
    p2_old = nomsg;
printf("POINT: 53\n");

    if ((int )m3 != (int )nomsg) {
printf("POINT: 54\n");
printf("POINT: 55\n");

      if (alive3) {
printf("POINT: 56\n");
printf("POINT: 57\n");

        if ((int )m3 > (int )id3) {
printf("POINT: 58\n");
          send3 = m3;
        } else
printf("POINT: 59\n");

        if ((int )m3 == (int )id3) {
printf("POINT: 60\n");
          st3 = (char)1;
        }
      } else {
printf("POINT: 62\n");
        send3 = m3;
      }
    }
    mode3 = (bool)0;
  } else {
printf("POINT: 64\n");
printf("POINT: 65\n");

    if (alive3) {
printf("POINT: 66\n");
    
    
printf("POINT: 67\n");

    if ((send3 != nomsg) && (p3_new == nomsg)){
printf("POINT: 68\n");
    p3_new = send3;
    }
    else{
    p3_new = p3_new;
    }
    
    
    } else
    {
printf("POINT: 69\n");

    if ((int )send3 != (int )id3) {
printf("POINT: 70\n");
    
printf("POINT: 71\n");

    if ((send3 != nomsg) && (p3_new == nomsg)){
printf("POINT: 72\n");
    p3_new = send3;
    }
    else{
    p3_new = p3_new;
    }
    
    }
    }
    mode3 = (bool)1;
  }
  return;
}
}
void node4(void) 
{ 
  msg_t m4 ;

  {
  m4 = nomsg;
printf("POINT: 73\n");

  if (mode4) {
printf("POINT: 74\n");
    m4 = p3_old;
    p3_old = nomsg;
printf("POINT: 75\n");

    if ((int )m4 != (int )nomsg) {
printf("POINT: 76\n");
printf("POINT: 77\n");

      if (alive4) {
printf("POINT: 78\n");
printf("POINT: 79\n");

        if ((int )m4 > (int )id4) {
printf("POINT: 80\n");
          send4 = m4;
        } else
printf("POINT: 81\n");

        if ((int )m4 == (int )id4) {
printf("POINT: 82\n");
          st4 = (char)1;
        }
      } else {
printf("POINT: 84\n");
        send4 = m4;
      }
    }
    mode4 = (bool)0;
  } else {
printf("POINT: 86\n");
printf("POINT: 87\n");

    if (alive4) {
printf("POINT: 88\n");
    
    
printf("POINT: 89\n");

    if ((send4 != nomsg) && (p4_new == nomsg)){
printf("POINT: 90\n");
    p4_new = send1;
    }
    else{
    p4_new = p4_new;
    }
    
    } else{
printf("POINT: 91\n");

    if ((int )send4 != (int )id4) {
printf("POINT: 92\n");
    
printf("POINT: 93\n");

    if ((send4 != nomsg) && (p4_new == nomsg)){
printf("POINT: 94\n");
    p4_new = send1;
    }
    else{
    p4_new = p4_new;
    }
    
    }
    }
    mode4 = (bool)1;
  }
  return;
}
}
void node5(void) 
{ 
  msg_t m5 ;

  {
  m5 = nomsg;
printf("POINT: 95\n");

  if (mode5) {
printf("POINT: 96\n");
    m5 = p4_old;
    p4_old = nomsg;
printf("POINT: 97\n");

    if ((int )m5 != (int )nomsg) {
printf("POINT: 98\n");
printf("POINT: 99\n");

      if (alive5) {
printf("POINT: 100\n");
printf("POINT: 101\n");

        if ((int )m5 > (int )id5) {
printf("POINT: 102\n");
          send5 = m5;
        } else
printf("POINT: 103\n");

        if ((int )m5 == (int )id5) {
printf("POINT: 104\n");
          st5 = (char)1;
        }
      } else {
printf("POINT: 106\n");
        send5 = m5;
      }
    }
    mode5 = (bool)0;
  } else {
printf("POINT: 108\n");
printf("POINT: 109\n");

    if (alive5) {
printf("POINT: 110\n");
printf("POINT: 111\n");

     if ((send5 != nomsg) && (p5_new == nomsg)){
printf("POINT: 112\n");
    p5_new = send5;
    }
    else{
    p5_new = p5_new;
    }
    
    
    } else
    {
printf("POINT: 113\n");

    if ((int )send5 != (int )id5) {
printf("POINT: 114\n");
    
printf("POINT: 115\n");

    if ((send5 != nomsg) && (p5_new == nomsg)){
printf("POINT: 116\n");
    p5_new = send5;
    }
    else{
    p5_new = p5_new;
    }
    }
    }
    mode5 = (bool)1;
  }
  return;
}
}
void node6(void) 
{ 
  msg_t m6 ;

  {
  m6 = nomsg;
printf("POINT: 117\n");

  if (mode6) {
printf("POINT: 118\n");
    m6 = p5_old;
    p5_old = nomsg;
printf("POINT: 119\n");

    if ((int )m6 != (int )nomsg) {
printf("POINT: 120\n");
printf("POINT: 121\n");

      if (alive6) {
printf("POINT: 122\n");
printf("POINT: 123\n");

        if ((int )m6 > (int )id6) {
printf("POINT: 124\n");
          send6 = m6;
        } else
printf("POINT: 125\n");

        if ((int )m6 == (int )id6) {
printf("POINT: 126\n");
          st6 = (char)1;
        }
      } else {
printf("POINT: 128\n");
        send6 = m6;
      }
    }
    mode6 = (bool)0;
  } else {
printf("POINT: 130\n");
printf("POINT: 131\n");

    if (alive6) {
printf("POINT: 132\n");
   
printf("POINT: 133\n");

   if ((send6 != nomsg) && (p6_new == nomsg)){
printf("POINT: 134\n");
    p6_new = send6;
    }
    else{
    p6_new = p6_new;
    }
   
    } else
    {
printf("POINT: 135\n");

    if ((int )send6 != (int )id6) {
printf("POINT: 136\n");
    
printf("POINT: 137\n");

    if ((send6 != nomsg) && (p6_new == nomsg)){
printf("POINT: 138\n");
    p6_new = send6;
    }
    else{
    p6_new = p6_new;
    }
    
    }
    }
    mode6 = (bool)1;
  }
  return;
}
}
void (*nodes[6])(void)  = {      & node1,      & node2,      & node3,      & node4, 
        & node5,      & node6};
int init(void) 
{ 
  int tmp ;

  {
printf("POINT: 139\n");

  if ((int )r1 == 0) {
printf("POINT: 140\n");
printf("POINT: 141\n");

    if ((((((int )alive1 + (int )alive2) + (int )alive3) + (int )alive4) + (int )alive5) + (int )alive6 >= 1) {
printf("POINT: 142\n");
printf("POINT: 143\n");

      if ((int )id1 >= 0) {
printf("POINT: 144\n");
printf("POINT: 145\n");

        if ((int )st1 == 0) {
printf("POINT: 146\n");
printf("POINT: 147\n");

          if ((int )send1 == (int )id1) {
printf("POINT: 148\n");
printf("POINT: 149\n");

            if ((int )mode1 == 0) {
printf("POINT: 150\n");
printf("POINT: 151\n");

              if ((int )id2 >= 0) {
printf("POINT: 152\n");
printf("POINT: 153\n");

                if ((int )st2 == 0) {
printf("POINT: 154\n");
printf("POINT: 155\n");

                  if ((int )send2 == (int )id2) {
printf("POINT: 156\n");
printf("POINT: 157\n");

                    if ((int )mode2 == 0) {
printf("POINT: 158\n");
printf("POINT: 159\n");

                      if ((int )id3 >= 0) {
printf("POINT: 160\n");
printf("POINT: 161\n");

                        if ((int )st3 == 0) {
printf("POINT: 162\n");
printf("POINT: 163\n");

                          if ((int )send3 == (int )id3) {
printf("POINT: 164\n");
printf("POINT: 165\n");

                            if ((int )mode3 == 0) {
printf("POINT: 166\n");
printf("POINT: 167\n");

                              if ((int )id4 >= 0) {
printf("POINT: 168\n");
printf("POINT: 169\n");

                                if ((int )st4 == 0) {
printf("POINT: 170\n");
printf("POINT: 171\n");

                                  if ((int )send4 == (int )id4) {
printf("POINT: 172\n");
printf("POINT: 173\n");

                                    if ((int )mode4 == 0) {
printf("POINT: 174\n");
printf("POINT: 175\n");

                                      if ((int )id5 >= 0) {
printf("POINT: 176\n");
printf("POINT: 177\n");

                                        if ((int )st5 == 0) {
printf("POINT: 178\n");
printf("POINT: 179\n");

                                          if ((int )send5 == (int )id5) {
printf("POINT: 180\n");
printf("POINT: 181\n");

                                            if ((int )mode5 == 0) {
printf("POINT: 182\n");
printf("POINT: 183\n");

                                              if ((int )id6 >= 0) {
printf("POINT: 184\n");
printf("POINT: 185\n");

                                                if ((int )st6 == 0) {
printf("POINT: 186\n");
printf("POINT: 187\n");

                                                  if ((int )send6 == (int )id6) {
printf("POINT: 188\n");
printf("POINT: 189\n");

                                                    if ((int )mode6 == 0) {
printf("POINT: 190\n");
printf("POINT: 191\n");

                                                      if ((int )id1 != (int )id2) {
printf("POINT: 192\n");
printf("POINT: 193\n");

                                                        if ((int )id1 != (int )id3) {
printf("POINT: 194\n");
printf("POINT: 195\n");

                                                          if ((int )id1 != (int )id4) {
printf("POINT: 196\n");
printf("POINT: 197\n");

                                                            if ((int )id1 != (int )id5) {
printf("POINT: 198\n");
printf("POINT: 199\n");

                                                              if ((int )id1 != (int )id6) {
printf("POINT: 200\n");
printf("POINT: 201\n");

                                                                if ((int )id2 != (int )id3) {
printf("POINT: 202\n");
printf("POINT: 203\n");

                                                                  if ((int )id2 != (int )id4) {
printf("POINT: 204\n");
printf("POINT: 205\n");

                                                                    if ((int )id2 != (int )id5) {
printf("POINT: 206\n");
printf("POINT: 207\n");

                                                                      if ((int )id2 != (int )id6) {
printf("POINT: 208\n");
printf("POINT: 209\n");

                                                                        if ((int )id3 != (int )id4) {
printf("POINT: 210\n");
printf("POINT: 211\n");

                                                                          if ((int )id3 != (int )id5) {
printf("POINT: 212\n");
printf("POINT: 213\n");

                                                                            if ((int )id3 != (int )id6) {
printf("POINT: 214\n");
printf("POINT: 215\n");

                                                                              if ((int )id4 != (int )id5) {
printf("POINT: 216\n");
printf("POINT: 217\n");

                                                                                if ((int )id4 != (int )id6) {
printf("POINT: 218\n");
printf("POINT: 219\n");

                                                                                  if ((int )id5 != (int )id6) {
printf("POINT: 220\n");
                                                                                    tmp = 1;
                                                                                  } else {
printf("POINT: 222\n");
                                                                                    tmp = 0;
                                                                                  }
                                                                                } else {
printf("POINT: 224\n");
                                                                                  tmp = 0;
                                                                                }
                                                                              } else {
printf("POINT: 226\n");
                                                                                tmp = 0;
                                                                              }
                                                                            } else {
printf("POINT: 228\n");
                                                                              tmp = 0;
                                                                            }
                                                                          } else {
printf("POINT: 230\n");
                                                                            tmp = 0;
                                                                          }
                                                                        } else {
printf("POINT: 232\n");
                                                                          tmp = 0;
                                                                        }
                                                                      } else {
printf("POINT: 234\n");
                                                                        tmp = 0;
                                                                      }
                                                                    } else {
printf("POINT: 236\n");
                                                                      tmp = 0;
                                                                    }
                                                                  } else {
printf("POINT: 238\n");
                                                                    tmp = 0;
                                                                  }
                                                                } else {
printf("POINT: 240\n");
                                                                  tmp = 0;
                                                                }
                                                              } else {
printf("POINT: 242\n");
                                                                tmp = 0;
                                                              }
                                                            } else {
printf("POINT: 244\n");
                                                              tmp = 0;
                                                            }
                                                          } else {
printf("POINT: 246\n");
                                                            tmp = 0;
                                                          }
                                                        } else {
printf("POINT: 248\n");
                                                          tmp = 0;
                                                        }
                                                      } else {
printf("POINT: 250\n");
                                                        tmp = 0;
                                                      }
                                                    } else {
printf("POINT: 252\n");
                                                      tmp = 0;
                                                    }
                                                  } else {
printf("POINT: 254\n");
                                                    tmp = 0;
                                                  }
                                                } else {
printf("POINT: 256\n");
                                                  tmp = 0;
                                                }
                                              } else {
printf("POINT: 258\n");
                                                tmp = 0;
                                              }
                                            } else {
printf("POINT: 260\n");
                                              tmp = 0;
                                            }
                                          } else {
printf("POINT: 262\n");
                                            tmp = 0;
                                          }
                                        } else {
printf("POINT: 264\n");
                                          tmp = 0;
                                        }
                                      } else {
printf("POINT: 266\n");
                                        tmp = 0;
                                      }
                                    } else {
printf("POINT: 268\n");
                                      tmp = 0;
                                    }
                                  } else {
printf("POINT: 270\n");
                                    tmp = 0;
                                  }
                                } else {
printf("POINT: 272\n");
                                  tmp = 0;
                                }
                              } else {
printf("POINT: 274\n");
                                tmp = 0;
                              }
                            } else {
printf("POINT: 276\n");
                              tmp = 0;
                            }
                          } else {
printf("POINT: 278\n");
                            tmp = 0;
                          }
                        } else {
printf("POINT: 280\n");
                          tmp = 0;
                        }
                      } else {
printf("POINT: 282\n");
                        tmp = 0;
                      }
                    } else {
printf("POINT: 284\n");
                      tmp = 0;
                    }
                  } else {
printf("POINT: 286\n");
                    tmp = 0;
                  }
                } else {
printf("POINT: 288\n");
                  tmp = 0;
                }
              } else {
printf("POINT: 290\n");
                tmp = 0;
              }
            } else {
printf("POINT: 292\n");
              tmp = 0;
            }
          } else {
printf("POINT: 294\n");
            tmp = 0;
          }
        } else {
printf("POINT: 296\n");
          tmp = 0;
        }
      } else {
printf("POINT: 298\n");
        tmp = 0;
      }
    } else {
printf("POINT: 300\n");
      tmp = 0;
    }
  } else {
printf("POINT: 302\n");
    tmp = 0;
  }
  return (tmp);
}
}
int check(void) 
{ 
  int tmp ;

  {
printf("POINT: 303\n");

  if ((((((int )st1 + (int )st2) + (int )st3) + (int )st4) + (int )st5) + (int )st6 <= 1) {
printf("POINT: 304\n");
printf("POINT: 305\n");

    if ((int )r1 < 6) {
printf("POINT: 306\n");
      tmp = 1;
    } else
printf("POINT: 307\n");

    if ((((((int )st1 + (int )st2) + (int )st3) + (int )st4) + (int )st5) + (int )st6 == 1) {
printf("POINT: 308\n");
      tmp = 1;
    } else {
printf("POINT: 310\n");
      tmp = 0;
    }
  } else {
printf("POINT: 312\n");
    tmp = 0;
  }
  return (tmp);
}
}



int main(void) 
{ 
  int c1 ;
  int i2 ;
  kappa = 0;
  {
  c1 = 0;
  
  r1 = nondet_char(); __CPROVER_input("r1",r1);
    
  id1 = nondet_char(); __CPROVER_input("id1",id1);
  st1 = nondet_char(); __CPROVER_input("st1",st1);
  send1 = nondet_char(); __CPROVER_input("send1",send1);
  mode1 = nondet_bool(); __CPROVER_input("mode1",mode1);
  alive1 = nondet_bool(); __CPROVER_input("alive1",alive1);

  id2 = nondet_char(); __CPROVER_input("id2",id2);
  st2 = nondet_char(); __CPROVER_input("st2",st2);
  send2 = nondet_char(); __CPROVER_input("send2",send2);
  mode2 = nondet_bool(); __CPROVER_input("mode2",mode2);
  alive2 = nondet_bool(); __CPROVER_input("alive2",alive2);
  
  id3 = nondet_char(); __CPROVER_input("id3",id3);
  st3 = nondet_char(); __CPROVER_input("st3",st3);
  send3 = nondet_char(); __CPROVER_input("send3",send3);
  mode3 = nondet_bool(); __CPROVER_input("mode3",mode3);
  alive3 = nondet_bool(); __CPROVER_input("alive3",alive3);
  
  
  id4 = nondet_char(); __CPROVER_input("id4",id4);
  st4 = nondet_char(); __CPROVER_input("st4",st4);
  send4 = nondet_char(); __CPROVER_input("send4",send4);
  mode4 = nondet_bool(); __CPROVER_input("mode4",mode4);
  alive4 = nondet_bool(); __CPROVER_input("alive4",alive4);

  id5 = nondet_char(); __CPROVER_input("id5",id5);
  st5 = nondet_char(); __CPROVER_input("st5",st5);
  send5 = nondet_char(); __CPROVER_input("send5",send5);
  mode5 = nondet_bool(); __CPROVER_input("mode5",mode5);
  alive5 = nondet_bool(); __CPROVER_input("alive5",alive5);
    
  id6 = nondet_char(); __CPROVER_input("id6",id6);
  st6 = nondet_char(); __CPROVER_input("st6",st6);
  send6 = nondet_char(); __CPROVER_input("send6",send6);
  mode6 = nondet_bool(); __CPROVER_input("mode6",mode6);
  alive6 = nondet_bool(); __CPROVER_input("alive6",alive6);
  
  i2 = init();
  p1_old = nomsg;
  p1_new = nomsg;
  p2_old = nomsg;
  p2_new = nomsg;
  p3_old = nomsg;
  p3_new = nomsg;
  p4_old = nomsg;
  p4_new = nomsg;
  p5_old = nomsg;
  p5_new = nomsg;
  p6_old = nomsg;
  p6_new = nomsg;
  i2 = 0;
printf("POINT: 313\n");

  while (i2 < 1) {
printf("POINT: 314\n");
    {
    node1();
    node2();
    node3();
    node4();
    node5();
    node6();
    p1_old = p1_new;
    p1_new = nomsg;
    p2_old = p2_new;
    p2_new = nomsg;
    p3_old = p3_new;
    p3_new = nomsg;
    p4_old = p4_new;
    p4_new = nomsg;
    p5_old = p5_new;
    p5_new = nomsg;
    p6_old = p6_new;
    p6_new = nomsg;
    c1 = check();
    i2++;
    }
  }
}

return 0;
}
