//This program is pals_floodmax.4_false-unreach-call.4.ufo.UNBOUNDED.pals.c







/**********************************************************************

Copyright (c) 2013 Carnegie Mellon University. All Rights Reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following acknowledgments and
disclaimers.

2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

3. The names "Carnegie Mellon University," "SEI" and/or "Software
Engineering Institute" shall not be used to endorse or promote
products derived from this software without prior written
permission. For written permission, please contact
permission@sei.cmu.edu.

4. Products derived from this software may not be called "SEI" nor may
"SEI" appear in their names without prior written permission of
permission@sei.cmu.edu.

5. Redistributions of any form whatsoever must retain the following
acknowledgment:

This material is based upon work funded and supported by the
Department of Defense under Contract No. FA8721-05-C-0003 with
Carnegie Mellon University for the operation of the Software
Engineering Institute, a federally funded research and development
center.

Any opinions, findings and conclusions or recommendations expressed in
this material are those of the author(s) and do not necessarily
reflect the views of the United States Department of Defense.

NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
INSTITUTE MATERIAL IS FURNISHEDON AN "AS-IS" BASIS. CARNEGIE MELLON
UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
TRADEMARK, OR COPYRIGHT INFRINGEMENT.

This material has been approved for public release and unlimited
distribution.

DM-0000575

**********************************************************************/

/* Generated by CIL v. 1.6.0 */
/* print_CIL_Input is true */
#include <stdlib.h>
#include <stdio.h> 
#include <assert.h>
int kappa;
typedef int bool;
#define true 1
#define false 0

typedef char msg_t;
typedef int port_t;
extern void read(port_t p , msg_t m ) ;
extern void write(port_t p , msg_t m ) ;
msg_t nomsg  =    (msg_t )-1;
port_t p12  ;
char p12_old ;
char p12_new ;
bool ep12  ;
port_t p13  ;
char p13_old ;
char p13_new ;
bool ep13  ;
port_t p14  ;
char p14_old ;
char p14_new ;
bool ep14  ;
port_t p21  ;
char p21_old ;
char p21_new ;
bool ep21  ;
port_t p23  ;
char p23_old ;
char p23_new ;
bool ep23  ;
port_t p24  ;
char p24_old ;
char p24_new ;
bool ep24  ;
port_t p31  ;
char p31_old ;
char p31_new ;
bool ep31  ;
port_t p32  ;
char p32_old ;
char p32_new ;
bool ep32  ;
port_t p34  ;
char p34_old ;
char p34_new ;
bool ep34  ;
port_t p41  ;
char p41_old ;
char p41_new ;
bool ep41  ;
port_t p42  ;
char p42_old ;
char p42_new ;
bool ep42  ;
port_t p43  ;
char p43_old ;
char p43_new ;
bool ep43  ;
char id1  ;
char r1  ;
char st1  ;
char nl1  ;
char m1  ;
char max1  ;
bool mode1  ;
char id2  ;
char r2  ;
char st2  ;
char nl2  ;
char m2  ;
char max2  ;
bool mode2  ;
char id3  ;
char r3  ;
char st3  ;
char nl3  ;
char m3  ;
char max3  ;
bool mode3  ;
char id4  ;
char r4  ;
char st4  ;
char nl4  ;
char m4  ;
char max4  ;
bool mode4  ;
void node1(void) 
{ 


  {
printf("POINT: 1\n");

  if (mode1) {
printf("POINT: 2\n");
printf("POINT: 3\n");

    if (r1 == 255) {
printf("POINT: 4\n");
      r1 = 3;
    }
    r1 = r1 + 1;
printf("POINT: 5\n");

    if (ep21) {
printf("POINT: 6\n");
      m1 = p21_old;
      p21_old = nomsg;
printf("POINT: 7\n");

      if ((int )m1 > (int )max1) {
printf("POINT: 8\n");
        max1 = m1;
      }
    }
printf("POINT: 9\n");

    if (ep31) {
printf("POINT: 10\n");
      m1 = p31_old;
      p31_old = nomsg;
printf("POINT: 11\n");

      if ((int )m1 > (int )max1) {
printf("POINT: 12\n");
        max1 = m1;
      }
    }
printf("POINT: 13\n");

    if (ep41) {
printf("POINT: 14\n");
      m1 = p41_old;
      p41_old = nomsg;
printf("POINT: 15\n");

      if ((int )m1 > (int )max1) {
printf("POINT: 16\n");
        max1 = m1;
      }
    }
printf("POINT: 17\n");

    if ((int )r1 == 3) {
printf("POINT: 18\n");
printf("POINT: 19\n");

      if ((int )max1 == (int )id1) {
printf("POINT: 20\n");
        st1 = (char)1;
      } else {
printf("POINT: 22\n");
        nl1 = (char)1;
      }
    }
    mode1 = (bool)0;
  } else {
printf("POINT: 24\n");
printf("POINT: 25\n");

    if ((int )r1 < 2) {
printf("POINT: 26\n");
printf("POINT: 27\n");

      if (ep12) {
printf("POINT: 28\n");
       
        
printf("POINT: 29\n");

    if ((max1 != nomsg) && (p12_new == nomsg)){
printf("POINT: 30\n");
    p12_new = max1;
    }
    else{
    p12_new = p12_new;
    }
    
    
        
      }
printf("POINT: 31\n");

      if (ep13) {
printf("POINT: 32\n");
        
printf("POINT: 33\n");

    if ((max1 != nomsg) && (p13_new == nomsg)){
printf("POINT: 34\n");
    p13_new = max1;
    }
    else{
    p13_new = p13_new;
    }
    
    
      }
printf("POINT: 35\n");

      if (ep14) {
printf("POINT: 36\n");
    
    
printf("POINT: 37\n");

    if ((max1 != nomsg) && (p14_new == nomsg)){
printf("POINT: 38\n");
    p14_new = max1;
    }
    else{
    p14_new = p14_new;
    }
    
    
      }
    }
    mode1 = (bool)1;
  }
  return;
}
}
void node2(void) 
{ 


  {
printf("POINT: 39\n");

  if (mode2) {
printf("POINT: 40\n");
printf("POINT: 41\n");

    if (r2 == 255) {
printf("POINT: 42\n");
      r2 = 3;
    }
    r2 = r2 + 1;
printf("POINT: 43\n");

    if (ep12) {
printf("POINT: 44\n");
      m2 = p12_old;
      p12_old = nomsg;
printf("POINT: 45\n");

      if ((int )m2 > (int )max2) {
printf("POINT: 46\n");
        max2 = m2;
      }
    }
printf("POINT: 47\n");

    if (ep32) {
printf("POINT: 48\n");
      m2 = p32_old;
      p32_old = nomsg;
printf("POINT: 49\n");

      if ((int )m2 > (int )max2) {
printf("POINT: 50\n");
        max2 = m2;
      }
    }
printf("POINT: 51\n");

    if (ep42) {
printf("POINT: 52\n");
      m2 = p42_old;
      p42_old = nomsg;
printf("POINT: 53\n");

      if ((int )m2 > (int )max2) {
printf("POINT: 54\n");
        max2 = m2;
      }
    }
printf("POINT: 55\n");

    if ((int )r2 == 3) {
printf("POINT: 56\n");
printf("POINT: 57\n");

      if ((int )max2 == (int )id2) {
printf("POINT: 58\n");
        st2 = (char)1;
      } else {
printf("POINT: 60\n");
        nl2 = (char)1;
      }
    }
    mode2 = (bool)0;
  } else {
printf("POINT: 62\n");
printf("POINT: 63\n");

    if ((int )r2 < 3) {
printf("POINT: 64\n");
printf("POINT: 65\n");

      if (ep21) {
printf("POINT: 66\n");
        
printf("POINT: 67\n");

    if ((max2 != nomsg) && (p21_new == nomsg)){
printf("POINT: 68\n");
    p21_new = max2;
    }
    else{
    p21_new = p21_new;
    }
        
      }
printf("POINT: 69\n");

      if (ep23) {
printf("POINT: 70\n");
       
printf("POINT: 71\n");

    if ((max2 != nomsg) && (p23_new == nomsg)){
printf("POINT: 72\n");
    p23_new = max2;
    }
    else{
    p23_new = p23_new;
    }
    
    
      }
printf("POINT: 73\n");

      if (ep24) {
printf("POINT: 74\n");
        
printf("POINT: 75\n");

    if ((max2 != nomsg) && (p24_new == nomsg)){
printf("POINT: 76\n");
    p24_new = max2;
    }
    else{
    p24_new = p24_new;
    }
        
      }
    }
    mode2 = (bool)1;
  }
  return;
}
}
void node3(void) 
{ 


  {
printf("POINT: 77\n");

  if (mode3) {
printf("POINT: 78\n");
printf("POINT: 79\n");

    if (r3 == 255) {
printf("POINT: 80\n");
      r3 = 3;
    }
    r3 = r3 + 1;
printf("POINT: 81\n");

    if (ep13) {
printf("POINT: 82\n");
      m3 = p13_old;
      p13_old = nomsg;
printf("POINT: 83\n");

      if ((int )m3 > (int )max3) {
printf("POINT: 84\n");
        max3 = m3;
      }
    }
printf("POINT: 85\n");

    if (ep23) {
printf("POINT: 86\n");
      m3 = p23_old;
      p23_old = nomsg;
printf("POINT: 87\n");

      if ((int )m3 > (int )max3) {
printf("POINT: 88\n");
        max3 = m3;
      }
    }
printf("POINT: 89\n");

    if (ep43) {
printf("POINT: 90\n");
      m3 = p43_old;
      p43_old = nomsg;
printf("POINT: 91\n");

      if ((int )m3 > (int )max3) {
printf("POINT: 92\n");
        max3 = m3;
      }
    }
printf("POINT: 93\n");

    if ((int )r3 == 3) {
printf("POINT: 94\n");
printf("POINT: 95\n");

      if ((int )max3 == (int )id3) {
printf("POINT: 96\n");
        st3 = (char)1;
      } else {
printf("POINT: 98\n");
        nl3 = (char)1;
      }
    }
    mode3 = (bool)0;
  } else {
printf("POINT: 100\n");
printf("POINT: 101\n");

    if ((int )r3 < 3) {
printf("POINT: 102\n");
printf("POINT: 103\n");

      if (ep31) {
printf("POINT: 104\n");

        
printf("POINT: 105\n");

    if ((max3 != nomsg) && (p31_new == nomsg)){
printf("POINT: 106\n");
    p31_new = max3;
    }
    else{
    p31_new = p31_new;
    }
        
      }
printf("POINT: 107\n");

      if (ep32) {
printf("POINT: 108\n");
        
printf("POINT: 109\n");

    if ((max3 != nomsg) && (p32_new == nomsg)){
printf("POINT: 110\n");
    p32_new = max3;
    }
    else{
    p32_new = p32_new;
    } 
        
      }
printf("POINT: 111\n");

      if (ep34) {
printf("POINT: 112\n");
    
printf("POINT: 113\n");

     if ((max3 != nomsg) && (p34_new == nomsg)){
printf("POINT: 114\n");
    p34_new = max3;
    }
    else{
    p34_new = p34_new;
    }
    
      }
    }
    mode3 = (bool)1;
  }
  return;
}
}
void node4(void) 
{ 


  {
printf("POINT: 115\n");

  if (mode4) {
printf("POINT: 116\n");
printf("POINT: 117\n");

    if (r4 == 255) {
printf("POINT: 118\n");
      r4 = 3;
    }
    r4 = r4 + 1;
printf("POINT: 119\n");

    if (ep14) {
printf("POINT: 120\n");
      m4 = p14_old;
      p14_old = nomsg;
printf("POINT: 121\n");

      if ((int )m4 > (int )max4) {
printf("POINT: 122\n");
        max4 = m4;
      }
    }
printf("POINT: 123\n");

    if (ep24) {
printf("POINT: 124\n");
      m4 = p24_old;
      p24_old = nomsg;
printf("POINT: 125\n");

      if ((int )m4 > (int )max4) {
printf("POINT: 126\n");
        max4 = m4;
      }
    }
printf("POINT: 127\n");

    if (ep34) {
printf("POINT: 128\n");
      m4 = p34_old;
      p34_old = nomsg;
printf("POINT: 129\n");

      if ((int )m4 > (int )max4) {
printf("POINT: 130\n");
        max4 = m4;
      }
    }
printf("POINT: 131\n");

    if ((int )r4 == 3) {
printf("POINT: 132\n");
printf("POINT: 133\n");

      if ((int )max4 == (int )id4) {
printf("POINT: 134\n");
        st4 = (char)1;
      } else {
printf("POINT: 136\n");
        nl4 = (char)1;
      }
    }
    mode4 = (bool)0;
  } else {
printf("POINT: 138\n");
printf("POINT: 139\n");

    if ((int )r4 < 3) {
printf("POINT: 140\n");
printf("POINT: 141\n");

      if (ep41) {
printf("POINT: 142\n");
        
printf("POINT: 143\n");

    if ((max4 != nomsg) && (p41_new == nomsg)){
printf("POINT: 144\n");
    p41_new = max4;
    }
    else{
    p41_new = p41_new;
    }
    
    
      }
printf("POINT: 145\n");

      if (ep42) {
printf("POINT: 146\n");

      
printf("POINT: 147\n");

      if ((max4 != nomsg) && (p42_new == nomsg)){
printf("POINT: 148\n");
    p42_new = max4;
    }
    else{
    p42_new = p42_new;
    }
    
      }
printf("POINT: 149\n");

      if (ep43) {
printf("POINT: 150\n");
        
        
printf("POINT: 151\n");

     if ((max4 != nomsg) && (p43_new == nomsg)){
printf("POINT: 152\n");
    p43_new = max4;
    }
    else{
    p43_new = p43_new;
    }
    
        
      }
    }
    mode4 = (bool)1;
  }
  return;
}
}
void (*nodes[4])(void)  = {      & node1,      & node2,      & node3,      & node4};
int init(void) 
{ 
  bool r121 ;
  bool r131 ;
  bool r141 ;
  bool r211 ;
  bool r231 ;
  bool r241 ;
  bool r311 ;
  bool r321 ;
  bool r341 ;
  bool r411 ;
  bool r421 ;
  bool r431 ;
  bool r122 ;
  int tmp ;
  bool r132 ;
  int tmp___0 ;
  bool r142 ;
  int tmp___1 ;
  bool r212 ;
  int tmp___2 ;
  bool r232 ;
  int tmp___3 ;
  bool r242 ;
  int tmp___4 ;
  bool r312 ;
  int tmp___5 ;
  bool r322 ;
  int tmp___6 ;
  bool r342 ;
  int tmp___7 ;
  bool r412 ;
  int tmp___8 ;
  bool r422 ;
  int tmp___9 ;
  bool r432 ;
  int tmp___10 ;
  bool r123 ;
  int tmp___11 ;
  bool r133 ;
  int tmp___12 ;
  bool r143 ;
  int tmp___13 ;
  bool r213 ;
  int tmp___14 ;
  bool r233 ;
  int tmp___15 ;
  bool r243 ;
  int tmp___16 ;
  bool r313 ;
  int tmp___17 ;
  bool r323 ;
  int tmp___18 ;
  bool r343 ;
  int tmp___19 ;
  bool r413 ;
  int tmp___20 ;
  bool r423 ;
  int tmp___21 ;
  bool r433 ;
  int tmp___22 ;
  int tmp___23 ;

  {
  r121 = ep12;
  r131 = ep13;
  r141 = ep14;
  r211 = ep21;
  r231 = ep23;
  r241 = ep24;
  r311 = ep31;
  r321 = ep32;
  r341 = ep34;
  r411 = ep41;
  r421 = ep42;
  r431 = ep43;
printf("POINT: 153\n");

  if (r121) {
printf("POINT: 154\n");
    tmp = 1;
printf("POINT: 155\n");

  } else if (r131) {
printf("POINT: 156\n");
printf("POINT: 157\n");

    if (ep32) {
printf("POINT: 158\n");
      tmp = 1;
    } else {
printf("POINT: 160\n");
      goto _L;
    }
  } else
  _L: /* CIL Label */ 
printf("POINT: 161\n");

  if (r141) {
printf("POINT: 162\n");
printf("POINT: 163\n");

    if (ep42) {
printf("POINT: 164\n");
      tmp = 1;
    } else {
printf("POINT: 166\n");
      tmp = 0;
    }
  } else {
printf("POINT: 168\n");
    tmp = 0;
  }
  r122 = (bool )tmp;
printf("POINT: 169\n");

  if (r131) {
printf("POINT: 170\n");
    tmp___0 = 1;
printf("POINT: 171\n");

  } else if (r121) {
printf("POINT: 172\n");
printf("POINT: 173\n");

    if (ep23) {
printf("POINT: 174\n");
      tmp___0 = 1;
    } else {
printf("POINT: 176\n");
      goto _L___0;
    }
  } else
  _L___0: /* CIL Label */ 
printf("POINT: 177\n");

  if (r141) {
printf("POINT: 178\n");
printf("POINT: 179\n");

    if (ep43) {
printf("POINT: 180\n");
      tmp___0 = 1;
    } else {
printf("POINT: 182\n");
      tmp___0 = 0;
    }
  } else {
printf("POINT: 184\n");
    tmp___0 = 0;
  }
  r132 = (bool )tmp___0;
printf("POINT: 185\n");

  if (r141) {
printf("POINT: 186\n");
    tmp___1 = 1;
printf("POINT: 187\n");

  } else if (r121) {
printf("POINT: 188\n");
printf("POINT: 189\n");

    if (ep24) {
printf("POINT: 190\n");
      tmp___1 = 1;
    } else {
printf("POINT: 192\n");
      goto _L___1;
    }
  } else
  _L___1: /* CIL Label */ 
printf("POINT: 193\n");

  if (r131) {
printf("POINT: 194\n");
printf("POINT: 195\n");

    if (ep34) {
printf("POINT: 196\n");
      tmp___1 = 1;
    } else {
printf("POINT: 198\n");
      tmp___1 = 0;
    }
  } else {
printf("POINT: 200\n");
    tmp___1 = 0;
  }
  r142 = (bool )tmp___1;
printf("POINT: 201\n");

  if (r211) {
printf("POINT: 202\n");
    tmp___2 = 1;
printf("POINT: 203\n");

  } else if (r231) {
printf("POINT: 204\n");
printf("POINT: 205\n");

    if (ep31) {
printf("POINT: 206\n");
      tmp___2 = 1;
    } else {
printf("POINT: 208\n");
      goto _L___2;
    }
  } else
  _L___2: /* CIL Label */ 
printf("POINT: 209\n");

  if (r241) {
printf("POINT: 210\n");
printf("POINT: 211\n");

    if (ep41) {
printf("POINT: 212\n");
      tmp___2 = 1;
    } else {
printf("POINT: 214\n");
      tmp___2 = 0;
    }
  } else {
printf("POINT: 216\n");
    tmp___2 = 0;
  }
  r212 = (bool )tmp___2;
printf("POINT: 217\n");

  if (r231) {
printf("POINT: 218\n");
    tmp___3 = 1;
printf("POINT: 219\n");

  } else if (r211) {
printf("POINT: 220\n");
printf("POINT: 221\n");

    if (ep13) {
printf("POINT: 222\n");
      tmp___3 = 1;
    } else {
printf("POINT: 224\n");
      goto _L___3;
    }
  } else
  _L___3: /* CIL Label */ 
printf("POINT: 225\n");

  if (r241) {
printf("POINT: 226\n");
printf("POINT: 227\n");

    if (ep43) {
printf("POINT: 228\n");
      tmp___3 = 1;
    } else {
printf("POINT: 230\n");
      tmp___3 = 0;
    }
  } else {
printf("POINT: 232\n");
    tmp___3 = 0;
  }
  r232 = (bool )tmp___3;
printf("POINT: 233\n");

  if (r241) {
printf("POINT: 234\n");
    tmp___4 = 1;
printf("POINT: 235\n");

  } else if (r211) {
printf("POINT: 236\n");
printf("POINT: 237\n");

    if (ep14) {
printf("POINT: 238\n");
      tmp___4 = 1;
    } else {
printf("POINT: 240\n");
      goto _L___4;
    }
  } else
  _L___4: /* CIL Label */ 
printf("POINT: 241\n");

  if (r231) {
printf("POINT: 242\n");
printf("POINT: 243\n");

    if (ep34) {
printf("POINT: 244\n");
      tmp___4 = 1;
    } else {
printf("POINT: 246\n");
      tmp___4 = 0;
    }
  } else {
printf("POINT: 248\n");
    tmp___4 = 0;
  }
  r242 = (bool )tmp___4;
printf("POINT: 249\n");

  if (r311) {
printf("POINT: 250\n");
    tmp___5 = 1;
printf("POINT: 251\n");

  } else if (r321) {
printf("POINT: 252\n");
printf("POINT: 253\n");

    if (ep21) {
printf("POINT: 254\n");
      tmp___5 = 1;
    } else {
printf("POINT: 256\n");
      goto _L___5;
    }
  } else
  _L___5: /* CIL Label */ 
printf("POINT: 257\n");

  if (r341) {
printf("POINT: 258\n");
printf("POINT: 259\n");

    if (ep41) {
printf("POINT: 260\n");
      tmp___5 = 1;
    } else {
printf("POINT: 262\n");
      tmp___5 = 0;
    }
  } else {
printf("POINT: 264\n");
    tmp___5 = 0;
  }
  r312 = (bool )tmp___5;
printf("POINT: 265\n");

  if (r321) {
printf("POINT: 266\n");
    tmp___6 = 1;
printf("POINT: 267\n");

  } else if (r311) {
printf("POINT: 268\n");
printf("POINT: 269\n");

    if (ep12) {
printf("POINT: 270\n");
      tmp___6 = 1;
    } else {
printf("POINT: 272\n");
      goto _L___6;
    }
  } else
  _L___6: /* CIL Label */ 
printf("POINT: 273\n");

  if (r341) {
printf("POINT: 274\n");
printf("POINT: 275\n");

    if (ep42) {
printf("POINT: 276\n");
      tmp___6 = 1;
    } else {
printf("POINT: 278\n");
      tmp___6 = 0;
    }
  } else {
printf("POINT: 280\n");
    tmp___6 = 0;
  }
  r322 = (bool )tmp___6;
printf("POINT: 281\n");

  if (r341) {
printf("POINT: 282\n");
    tmp___7 = 1;
printf("POINT: 283\n");

  } else if (r311) {
printf("POINT: 284\n");
printf("POINT: 285\n");

    if (ep14) {
printf("POINT: 286\n");
      tmp___7 = 1;
    } else {
printf("POINT: 288\n");
      goto _L___7;
    }
  } else
  _L___7: /* CIL Label */ 
printf("POINT: 289\n");

  if (r321) {
printf("POINT: 290\n");
printf("POINT: 291\n");

    if (ep24) {
printf("POINT: 292\n");
      tmp___7 = 1;
    } else {
printf("POINT: 294\n");
      tmp___7 = 0;
    }
  } else {
printf("POINT: 296\n");
    tmp___7 = 0;
  }
  r342 = (bool )tmp___7;
printf("POINT: 297\n");

  if (r411) {
printf("POINT: 298\n");
    tmp___8 = 1;
printf("POINT: 299\n");

  } else if (r421) {
printf("POINT: 300\n");
printf("POINT: 301\n");

    if (ep21) {
printf("POINT: 302\n");
      tmp___8 = 1;
    } else {
printf("POINT: 304\n");
      goto _L___8;
    }
  } else
  _L___8: /* CIL Label */ 
printf("POINT: 305\n");

  if (r431) {
printf("POINT: 306\n");
printf("POINT: 307\n");

    if (ep31) {
printf("POINT: 308\n");
      tmp___8 = 1;
    } else {
printf("POINT: 310\n");
      tmp___8 = 0;
    }
  } else {
printf("POINT: 312\n");
    tmp___8 = 0;
  }
  r412 = (bool )tmp___8;
printf("POINT: 313\n");

  if (r421) {
printf("POINT: 314\n");
    tmp___9 = 1;
printf("POINT: 315\n");

  } else if (r411) {
printf("POINT: 316\n");
printf("POINT: 317\n");

    if (ep12) {
printf("POINT: 318\n");
      tmp___9 = 1;
    } else {
printf("POINT: 320\n");
      goto _L___9;
    }
  } else
  _L___9: /* CIL Label */ 
printf("POINT: 321\n");

  if (r431) {
printf("POINT: 322\n");
printf("POINT: 323\n");

    if (ep32) {
printf("POINT: 324\n");
      tmp___9 = 1;
    } else {
printf("POINT: 326\n");
      tmp___9 = 0;
    }
  } else {
printf("POINT: 328\n");
    tmp___9 = 0;
  }
  r422 = (bool )tmp___9;
printf("POINT: 329\n");

  if (r431) {
printf("POINT: 330\n");
    tmp___10 = 1;
printf("POINT: 331\n");

  } else if (r411) {
printf("POINT: 332\n");
printf("POINT: 333\n");

    if (ep13) {
printf("POINT: 334\n");
      tmp___10 = 1;
    } else {
printf("POINT: 336\n");
      goto _L___10;
    }
  } else
  _L___10: /* CIL Label */ 
printf("POINT: 337\n");

  if (r421) {
printf("POINT: 338\n");
printf("POINT: 339\n");

    if (ep23) {
printf("POINT: 340\n");
      tmp___10 = 1;
    } else {
printf("POINT: 342\n");
      tmp___10 = 0;
    }
  } else {
printf("POINT: 344\n");
    tmp___10 = 0;
  }
  r432 = (bool )tmp___10;
printf("POINT: 345\n");

  if (r122) {
printf("POINT: 346\n");
    tmp___11 = 1;
printf("POINT: 347\n");

  } else if (r132) {
printf("POINT: 348\n");
printf("POINT: 349\n");

    if (ep32) {
printf("POINT: 350\n");
      tmp___11 = 1;
    } else {
printf("POINT: 352\n");
      goto _L___11;
    }
  } else
  _L___11: /* CIL Label */ 
printf("POINT: 353\n");

  if (r142) {
printf("POINT: 354\n");
printf("POINT: 355\n");

    if (ep42) {
printf("POINT: 356\n");
      tmp___11 = 1;
    } else {
printf("POINT: 358\n");
      tmp___11 = 0;
    }
  } else {
printf("POINT: 360\n");
    tmp___11 = 0;
  }
  r123 = (bool )tmp___11;
printf("POINT: 361\n");

  if (r132) {
printf("POINT: 362\n");
    tmp___12 = 1;
printf("POINT: 363\n");

  } else if (r122) {
printf("POINT: 364\n");
printf("POINT: 365\n");

    if (ep23) {
printf("POINT: 366\n");
      tmp___12 = 1;
    } else {
printf("POINT: 368\n");
      goto _L___12;
    }
  } else
  _L___12: /* CIL Label */ 
printf("POINT: 369\n");

  if (r142) {
printf("POINT: 370\n");
printf("POINT: 371\n");

    if (ep43) {
printf("POINT: 372\n");
      tmp___12 = 1;
    } else {
printf("POINT: 374\n");
      tmp___12 = 0;
    }
  } else {
printf("POINT: 376\n");
    tmp___12 = 0;
  }
  r133 = (bool )tmp___12;
printf("POINT: 377\n");

  if (r142) {
printf("POINT: 378\n");
    tmp___13 = 1;
printf("POINT: 379\n");

  } else if (r122) {
printf("POINT: 380\n");
printf("POINT: 381\n");

    if (ep24) {
printf("POINT: 382\n");
      tmp___13 = 1;
    } else {
printf("POINT: 384\n");
      goto _L___13;
    }
  } else
  _L___13: /* CIL Label */ 
printf("POINT: 385\n");

  if (r132) {
printf("POINT: 386\n");
printf("POINT: 387\n");

    if (ep34) {
printf("POINT: 388\n");
      tmp___13 = 1;
    } else {
printf("POINT: 390\n");
      tmp___13 = 0;
    }
  } else {
printf("POINT: 392\n");
    tmp___13 = 0;
  }
  r143 = (bool )tmp___13;
printf("POINT: 393\n");

  if (r212) {
printf("POINT: 394\n");
    tmp___14 = 1;
printf("POINT: 395\n");

  } else if (r232) {
printf("POINT: 396\n");
printf("POINT: 397\n");

    if (ep31) {
printf("POINT: 398\n");
      tmp___14 = 1;
    } else {
printf("POINT: 400\n");
      goto _L___14;
    }
  } else
  _L___14: /* CIL Label */ 
printf("POINT: 401\n");

  if (r242) {
printf("POINT: 402\n");
printf("POINT: 403\n");

    if (ep41) {
printf("POINT: 404\n");
      tmp___14 = 1;
    } else {
printf("POINT: 406\n");
      tmp___14 = 0;
    }
  } else {
printf("POINT: 408\n");
    tmp___14 = 0;
  }
  r213 = (bool )tmp___14;
printf("POINT: 409\n");

  if (r232) {
printf("POINT: 410\n");
    tmp___15 = 1;
printf("POINT: 411\n");

  } else if (r212) {
printf("POINT: 412\n");
printf("POINT: 413\n");

    if (ep13) {
printf("POINT: 414\n");
      tmp___15 = 1;
    } else {
printf("POINT: 416\n");
      goto _L___15;
    }
  } else
  _L___15: /* CIL Label */ 
printf("POINT: 417\n");

  if (r242) {
printf("POINT: 418\n");
printf("POINT: 419\n");

    if (ep43) {
printf("POINT: 420\n");
      tmp___15 = 1;
    } else {
printf("POINT: 422\n");
      tmp___15 = 0;
    }
  } else {
printf("POINT: 424\n");
    tmp___15 = 0;
  }
  r233 = (bool )tmp___15;
printf("POINT: 425\n");

  if (r242) {
printf("POINT: 426\n");
    tmp___16 = 1;
printf("POINT: 427\n");

  } else if (r212) {
printf("POINT: 428\n");
printf("POINT: 429\n");

    if (ep14) {
printf("POINT: 430\n");
      tmp___16 = 1;
    } else {
printf("POINT: 432\n");
      goto _L___16;
    }
  } else
  _L___16: /* CIL Label */ 
printf("POINT: 433\n");

  if (r232) {
printf("POINT: 434\n");
printf("POINT: 435\n");

    if (ep34) {
printf("POINT: 436\n");
      tmp___16 = 1;
    } else {
printf("POINT: 438\n");
      tmp___16 = 0;
    }
  } else {
printf("POINT: 440\n");
    tmp___16 = 0;
  }
  r243 = (bool )tmp___16;
printf("POINT: 441\n");

  if (r312) {
printf("POINT: 442\n");
    tmp___17 = 1;
printf("POINT: 443\n");

  } else if (r322) {
printf("POINT: 444\n");
printf("POINT: 445\n");

    if (ep21) {
printf("POINT: 446\n");
      tmp___17 = 1;
    } else {
printf("POINT: 448\n");
      goto _L___17;
    }
  } else
  _L___17: /* CIL Label */ 
printf("POINT: 449\n");

  if (r342) {
printf("POINT: 450\n");
printf("POINT: 451\n");

    if (ep41) {
printf("POINT: 452\n");
      tmp___17 = 1;
    } else {
printf("POINT: 454\n");
      tmp___17 = 0;
    }
  } else {
printf("POINT: 456\n");
    tmp___17 = 0;
  }
  r313 = (bool )tmp___17;
printf("POINT: 457\n");

  if (r322) {
printf("POINT: 458\n");
    tmp___18 = 1;
printf("POINT: 459\n");

  } else if (r312) {
printf("POINT: 460\n");
printf("POINT: 461\n");

    if (ep12) {
printf("POINT: 462\n");
      tmp___18 = 1;
    } else {
printf("POINT: 464\n");
      goto _L___18;
    }
  } else
  _L___18: /* CIL Label */ 
printf("POINT: 465\n");

  if (r342) {
printf("POINT: 466\n");
printf("POINT: 467\n");

    if (ep42) {
printf("POINT: 468\n");
      tmp___18 = 1;
    } else {
printf("POINT: 470\n");
      tmp___18 = 0;
    }
  } else {
printf("POINT: 472\n");
    tmp___18 = 0;
  }
  r323 = (bool )tmp___18;
printf("POINT: 473\n");

  if (r342) {
printf("POINT: 474\n");
    tmp___19 = 1;
printf("POINT: 475\n");

  } else if (r312) {
printf("POINT: 476\n");
printf("POINT: 477\n");

    if (ep14) {
printf("POINT: 478\n");
      tmp___19 = 1;
    } else {
printf("POINT: 480\n");
      goto _L___19;
    }
  } else
  _L___19: /* CIL Label */ 
printf("POINT: 481\n");

  if (r322) {
printf("POINT: 482\n");
printf("POINT: 483\n");

    if (ep24) {
printf("POINT: 484\n");
      tmp___19 = 1;
    } else {
printf("POINT: 486\n");
      tmp___19 = 0;
    }
  } else {
printf("POINT: 488\n");
    tmp___19 = 0;
  }
  r343 = (bool )tmp___19;
printf("POINT: 489\n");

  if (r412) {
printf("POINT: 490\n");
    tmp___20 = 1;
printf("POINT: 491\n");

  } else if (r422) {
printf("POINT: 492\n");
printf("POINT: 493\n");

    if (ep21) {
printf("POINT: 494\n");
      tmp___20 = 1;
    } else {
printf("POINT: 496\n");
      goto _L___20;
    }
  } else
  _L___20: /* CIL Label */ 
printf("POINT: 497\n");

  if (r432) {
printf("POINT: 498\n");
printf("POINT: 499\n");

    if (ep31) {
printf("POINT: 500\n");
      tmp___20 = 1;
    } else {
printf("POINT: 502\n");
      tmp___20 = 0;
    }
  } else {
printf("POINT: 504\n");
    tmp___20 = 0;
  }
  r413 = (bool )tmp___20;
printf("POINT: 505\n");

  if (r422) {
printf("POINT: 506\n");
    tmp___21 = 1;
printf("POINT: 507\n");

  } else if (r412) {
printf("POINT: 508\n");
printf("POINT: 509\n");

    if (ep12) {
printf("POINT: 510\n");
      tmp___21 = 1;
    } else {
printf("POINT: 512\n");
      goto _L___21;
    }
  } else
  _L___21: /* CIL Label */ 
printf("POINT: 513\n");

  if (r432) {
printf("POINT: 514\n");
printf("POINT: 515\n");

    if (ep32) {
printf("POINT: 516\n");
      tmp___21 = 1;
    } else {
printf("POINT: 518\n");
      tmp___21 = 0;
    }
  } else {
printf("POINT: 520\n");
    tmp___21 = 0;
  }
  r423 = (bool )tmp___21;
printf("POINT: 521\n");

  if (r432) {
printf("POINT: 522\n");
    tmp___22 = 1;
printf("POINT: 523\n");

  } else if (r412) {
printf("POINT: 524\n");
printf("POINT: 525\n");

    if (ep13) {
printf("POINT: 526\n");
      tmp___22 = 1;
    } else {
printf("POINT: 528\n");
      goto _L___22;
    }
  } else
  _L___22: /* CIL Label */ 
printf("POINT: 529\n");

  if (r422) {
printf("POINT: 530\n");
printf("POINT: 531\n");

    if (ep23) {
printf("POINT: 532\n");
      tmp___22 = 1;
    } else {
printf("POINT: 534\n");
      tmp___22 = 0;
    }
  } else {
printf("POINT: 536\n");
    tmp___22 = 0;
  }
  r433 = (bool )tmp___22;
printf("POINT: 537\n");

  if ((int )id1 != (int )id2) {
printf("POINT: 538\n");
printf("POINT: 539\n");

    if ((int )id1 != (int )id3) {
printf("POINT: 540\n");
printf("POINT: 541\n");

      if ((int )id1 != (int )id4) {
printf("POINT: 542\n");
printf("POINT: 543\n");

        if ((int )id2 != (int )id3) {
printf("POINT: 544\n");
printf("POINT: 545\n");

          if ((int )id2 != (int )id4) {
printf("POINT: 546\n");
printf("POINT: 547\n");

            if ((int )id3 != (int )id4) {
printf("POINT: 548\n");
printf("POINT: 549\n");

              if ((int )id1 >= 0) {
printf("POINT: 550\n");
printf("POINT: 551\n");

                if ((int )id2 >= 0) {
printf("POINT: 552\n");
printf("POINT: 553\n");

                  if ((int )id3 >= 0) {
printf("POINT: 554\n");
printf("POINT: 555\n");

                    if ((int )id4 >= 0) {
printf("POINT: 556\n");
printf("POINT: 557\n");

                      if ((int )r1 == 0) {
printf("POINT: 558\n");
printf("POINT: 559\n");

                        if ((int )r2 == 0) {
printf("POINT: 560\n");
printf("POINT: 561\n");

                          if ((int )r3 == 0) {
printf("POINT: 562\n");
printf("POINT: 563\n");

                            if ((int )r4 == 0) {
printf("POINT: 564\n");
printf("POINT: 565\n");

                              if (r123) {
printf("POINT: 566\n");
printf("POINT: 567\n");

                                if (r133) {
printf("POINT: 568\n");
printf("POINT: 569\n");

                                  if (r143) {
printf("POINT: 570\n");
printf("POINT: 571\n");

                                    if (r213) {
printf("POINT: 572\n");
printf("POINT: 573\n");

                                      if (r233) {
printf("POINT: 574\n");
printf("POINT: 575\n");

                                        if (r243) {
printf("POINT: 576\n");
printf("POINT: 577\n");

                                          if (r313) {
printf("POINT: 578\n");
printf("POINT: 579\n");

                                            if (r323) {
printf("POINT: 580\n");
printf("POINT: 581\n");

                                              if (r343) {
printf("POINT: 582\n");
printf("POINT: 583\n");

                                                if (r413) {
printf("POINT: 584\n");
printf("POINT: 585\n");

                                                  if (r423) {
printf("POINT: 586\n");
printf("POINT: 587\n");

                                                    if (r433) {
printf("POINT: 588\n");
printf("POINT: 589\n");

                                                      if ((int )max1 == (int )id1) {
printf("POINT: 590\n");
printf("POINT: 591\n");

                                                        if ((int )max2 == (int )id2) {
printf("POINT: 592\n");
printf("POINT: 593\n");

                                                          if ((int )max3 == (int )id3) {
printf("POINT: 594\n");
printf("POINT: 595\n");

                                                            if ((int )max4 == (int )id4) {
printf("POINT: 596\n");
printf("POINT: 597\n");

                                                              if ((int )st1 == 0) {
printf("POINT: 598\n");
printf("POINT: 599\n");

                                                                if ((int )st2 == 0) {
printf("POINT: 600\n");
printf("POINT: 601\n");

                                                                  if ((int )st3 == 0) {
printf("POINT: 602\n");
printf("POINT: 603\n");

                                                                    if ((int )st4 == 0) {
printf("POINT: 604\n");
printf("POINT: 605\n");

                                                                      if ((int )nl1 == 0) {
printf("POINT: 606\n");
printf("POINT: 607\n");

                                                                        if ((int )nl2 == 0) {
printf("POINT: 608\n");
printf("POINT: 609\n");

                                                                          if ((int )nl3 == 0) {
printf("POINT: 610\n");
printf("POINT: 611\n");

                                                                            if ((int )nl4 == 0) {
printf("POINT: 612\n");
printf("POINT: 613\n");

                                                                              if ((int )mode1 == 0) {
printf("POINT: 614\n");
printf("POINT: 615\n");

                                                                                if ((int )mode2 == 0) {
printf("POINT: 616\n");
printf("POINT: 617\n");

                                                                                  if ((int )mode3 == 0) {
printf("POINT: 618\n");
printf("POINT: 619\n");

                                                                                    if ((int )mode4 == 0) {
printf("POINT: 620\n");
                                                                                      tmp___23 = 1;
                                                                                    } else {
printf("POINT: 622\n");
                                                                                      tmp___23 = 0;
                                                                                    }
                                                                                  } else {
printf("POINT: 624\n");
                                                                                    tmp___23 = 0;
                                                                                  }
                                                                                } else {
printf("POINT: 626\n");
                                                                                  tmp___23 = 0;
                                                                                }
                                                                              } else {
printf("POINT: 628\n");
                                                                                tmp___23 = 0;
                                                                              }
                                                                            } else {
printf("POINT: 630\n");
                                                                              tmp___23 = 0;
                                                                            }
                                                                          } else {
printf("POINT: 632\n");
                                                                            tmp___23 = 0;
                                                                          }
                                                                        } else {
printf("POINT: 634\n");
                                                                          tmp___23 = 0;
                                                                        }
                                                                      } else {
printf("POINT: 636\n");
                                                                        tmp___23 = 0;
                                                                      }
                                                                    } else {
printf("POINT: 638\n");
                                                                      tmp___23 = 0;
                                                                    }
                                                                  } else {
printf("POINT: 640\n");
                                                                    tmp___23 = 0;
                                                                  }
                                                                } else {
printf("POINT: 642\n");
                                                                  tmp___23 = 0;
                                                                }
                                                              } else {
printf("POINT: 644\n");
                                                                tmp___23 = 0;
                                                              }
                                                            } else {
printf("POINT: 646\n");
                                                              tmp___23 = 0;
                                                            }
                                                          } else {
printf("POINT: 648\n");
                                                            tmp___23 = 0;
                                                          }
                                                        } else {
printf("POINT: 650\n");
                                                          tmp___23 = 0;
                                                        }
                                                      } else {
printf("POINT: 652\n");
                                                        tmp___23 = 0;
                                                      }
                                                    } else {
printf("POINT: 654\n");
                                                      tmp___23 = 0;
                                                    }
                                                  } else {
printf("POINT: 656\n");
                                                    tmp___23 = 0;
                                                  }
                                                } else {
printf("POINT: 658\n");
                                                  tmp___23 = 0;
                                                }
                                              } else {
printf("POINT: 660\n");
                                                tmp___23 = 0;
                                              }
                                            } else {
printf("POINT: 662\n");
                                              tmp___23 = 0;
                                            }
                                          } else {
printf("POINT: 664\n");
                                            tmp___23 = 0;
                                          }
                                        } else {
printf("POINT: 666\n");
                                          tmp___23 = 0;
                                        }
                                      } else {
printf("POINT: 668\n");
                                        tmp___23 = 0;
                                      }
                                    } else {
printf("POINT: 670\n");
                                      tmp___23 = 0;
                                    }
                                  } else {
printf("POINT: 672\n");
                                    tmp___23 = 0;
                                  }
                                } else {
printf("POINT: 674\n");
                                  tmp___23 = 0;
                                }
                              } else {
printf("POINT: 676\n");
                                tmp___23 = 0;
                              }
                            } else {
printf("POINT: 678\n");
                              tmp___23 = 0;
                            }
                          } else {
printf("POINT: 680\n");
                            tmp___23 = 0;
                          }
                        } else {
printf("POINT: 682\n");
                          tmp___23 = 0;
                        }
                      } else {
printf("POINT: 684\n");
                        tmp___23 = 0;
                      }
                    } else {
printf("POINT: 686\n");
                      tmp___23 = 0;
                    }
                  } else {
printf("POINT: 688\n");
                    tmp___23 = 0;
                  }
                } else {
printf("POINT: 690\n");
                  tmp___23 = 0;
                }
              } else {
printf("POINT: 692\n");
                tmp___23 = 0;
              }
            } else {
printf("POINT: 694\n");
              tmp___23 = 0;
            }
          } else {
printf("POINT: 696\n");
            tmp___23 = 0;
          }
        } else {
printf("POINT: 698\n");
          tmp___23 = 0;
        }
      } else {
printf("POINT: 700\n");
        tmp___23 = 0;
      }
    } else {
printf("POINT: 702\n");
      tmp___23 = 0;
    }
  } else {
printf("POINT: 704\n");
    tmp___23 = 0;
  }
  return (tmp___23);
}
}
int check(void) 
{ 
  int tmp ;

  {
printf("POINT: 705\n");

  if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 <= 1) {
printf("POINT: 706\n");
printf("POINT: 707\n");

    if ((int )st1 + (int )nl1 <= 1) {
printf("POINT: 708\n");
printf("POINT: 709\n");

      if ((int )st2 + (int )nl2 <= 1) {
printf("POINT: 710\n");
printf("POINT: 711\n");

        if ((int )st3 + (int )nl3 <= 1) {
printf("POINT: 712\n");
printf("POINT: 713\n");

          if ((int )st4 + (int )nl4 <= 1) {
printf("POINT: 714\n");
printf("POINT: 715\n");

            if ((int )r1 >= 3) {
printf("POINT: 716\n");
              goto _L___1;
printf("POINT: 717\n");

            } else if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 == 0) {
printf("POINT: 718\n");
              _L___1: /* CIL Label */ 
printf("POINT: 719\n");

              if ((int )r1 < 3) {
printf("POINT: 720\n");
                goto _L___0;
printf("POINT: 721\n");

              } else if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 == 1) {
printf("POINT: 722\n");
                _L___0: /* CIL Label */ 
printf("POINT: 723\n");

                if ((int )r1 >= 3) {
printf("POINT: 724\n");
                  goto _L;
printf("POINT: 725\n");

                } else if ((((int )nl1 + (int )nl2) + (int )nl3) + (int )nl4 == 0) {
printf("POINT: 726\n");
                  _L: /* CIL Label */ 
printf("POINT: 727\n");

                  if ((int )r1 < 3) {
printf("POINT: 728\n");
                    tmp = 1;
printf("POINT: 729\n");

                  } else if ((((int )nl1 + (int )nl2) + (int )nl3) + (int )nl4 == 3) {
printf("POINT: 730\n");
                    tmp = 1;
                  } else {
printf("POINT: 732\n");
                    tmp = 0;
                  }
                } else {
printf("POINT: 734\n");
                  tmp = 0;
                }
              } else {
printf("POINT: 736\n");
                tmp = 0;
              }
            } else {
printf("POINT: 738\n");
              tmp = 0;
            }
          } else {
printf("POINT: 740\n");
            tmp = 0;
          }
        } else {
printf("POINT: 742\n");
          tmp = 0;
        }
      } else {
printf("POINT: 744\n");
        tmp = 0;
      }
    } else {
printf("POINT: 746\n");
      tmp = 0;
    }
  } else {
printf("POINT: 748\n");
    tmp = 0;
  }
  return (tmp);
}
}



int main(void) 
{ 
  int c1 ;
  int i2 ;
  kappa = 0;
  {
  c1 = 0;
  
  scanf("%", &ep12);
  scanf("%", &ep13);
  scanf("%", &ep14);
  
  
  scanf("%", &ep21);
  scanf("%", &ep23);
  scanf("%", &ep24);
  
  scanf("%", &ep31);
  scanf("%", &ep32);
  scanf("%", &ep34);
  
  scanf("%", &ep41);
  scanf("%", &ep42);
  scanf("%", &ep43);
  
  
  
   
  scanf("%c", &id1);
  scanf("%c", &r1);
  scanf("%c", &st1);
  scanf("%c", &nl1);
  scanf("%c", &m1);
  scanf("%c", &max1);
  scanf("%", &mode1);
  
  scanf("%c", &id2);
  scanf("%c", &r2);
  scanf("%c", &st2);
  scanf("%c", &nl2);
  scanf("%c", &m2);
  scanf("%c", &max2);
  scanf("%", &mode2);
  
  scanf("%c", &id3);
  scanf("%c", &r3);
  scanf("%c", &st3);
  scanf("%c", &nl3);
  scanf("%c", &m3);
  scanf("%c", &max3);
  scanf("%", &mode3);
  
  
  scanf("%c", &id4);
  scanf("%c", &r4);
  scanf("%c", &st4);
  scanf("%c", &nl4);
  scanf("%c", &m4);
  scanf("%c", &max4);
  scanf("%", &mode4);
  
  
  i2 = init();

  p12_old = nomsg;
  p12_new = nomsg;
  p13_old = nomsg;
  p13_new = nomsg;
  p14_old = nomsg;
  p14_new = nomsg;
  p21_old = nomsg;
  p21_new = nomsg;
  p23_old = nomsg;
  p23_new = nomsg;
  p24_old = nomsg;
  p24_new = nomsg;
  p31_old = nomsg;
  p31_new = nomsg;
  p32_old = nomsg;
  p32_new = nomsg;
  p34_old = nomsg;
  p34_new = nomsg;
  p41_old = nomsg;
  p41_new = nomsg;
  p42_old = nomsg;
  p42_new = nomsg;
  p43_old = nomsg;
  p43_new = nomsg;
  i2 = 0;
printf("POINT: 749\n");

    while (i2 < 1) {
printf("POINT: 750\n");
    {
    node1();
    node2();
    node3();
    node4();
    p12_old = p12_new;
    p12_new = nomsg;
    p13_old = p13_new;
    p13_new = nomsg;
    p14_old = p14_new;
    p14_new = nomsg;
    p21_old = p21_new;
    p21_new = nomsg;
    p23_old = p23_new;
    p23_new = nomsg;
    p24_old = p24_new;
    p24_new = nomsg;
    p31_old = p31_new;
    p31_new = nomsg;
    p32_old = p32_new;
    p32_new = nomsg;
    p34_old = p34_new;
    p34_new = nomsg;
    p41_old = p41_new;
    p41_new = nomsg;
    p42_old = p42_new;
    p42_new = nomsg;
    p43_old = p43_new;
    p43_new = nomsg;
    c1 = check();
    i2++;
    }
  }
}
return 0;
}

