//This proram is pals_floodmax.3_false-unreach-call.4.ufo.UNBOUNDED.pals.c







/**********************************************************************

Copyright (c) 2013 Carnegie Mellon University. All Rights Reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following acknowledgments and
disclaimers.

2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

3. The names "Carnegie Mellon University," "SEI" and/or "Software
Engineering Institute" shall not be used to endorse or promote
products derived from this software without prior written
permission. For written permission, please contact
permission@sei.cmu.edu.

4. Products derived from this software may not be called "SEI" nor may
"SEI" appear in their names without prior written permission of
permission@sei.cmu.edu.

5. Redistributions of any form whatsoever must retain the following
acknowledgment:

This material is based upon work funded and supported by the
Department of Defense under Contract No. FA8721-05-C-0003 with
Carnegie Mellon University for the operation of the Software
Engineering Institute, a federally funded research and development
center.

Any opinions, findings and conclusions or recommendations expressed in
this material are those of the author(s) and do not necessarily
reflect the views of the United States Department of Defense.

NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
INSTITUTE MATERIAL IS FURNISHEDON AN "AS-IS" BASIS. CARNEGIE MELLON
UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
TRADEMARK, OR COPYRIGHT INFRINGEMENT.

This material has been approved for public release and unlimited
distribution.

DM-0000575

**********************************************************************/

/* Generated by CIL v. 1.6.0 */
/* print_CIL_Input is true */
#include <stdlib.h>
#include <stdio.h> 
#include <assert.h>
int kappa;
typedef int bool;
#define true 1
#define false 0

typedef char msg_t;
typedef int port_t;
extern void read(port_t p , msg_t m ) ;
extern void write(port_t p , msg_t m ) ;
msg_t nomsg  =    (msg_t )-1;
port_t p12  ;
char p12_old ;
char p12_new ;
bool ep12  ;
port_t p13  ;
char p13_old ;
char p13_new ;
bool ep13  ;
port_t p21  ;
char p21_old ;
char p21_new ;
bool ep21  ;
port_t p23  ;
char p23_old ;
char p23_new ;
bool ep23  ;
port_t p31  ;
char p31_old ;
char p31_new ;
bool ep31  ;
port_t p32  ;
char p32_old ;
char p32_new ;
bool ep32  ;
char id1  ;
char r1  ;
char st1  ;
char nl1  ;
char m1  ;
char max1  ;
bool mode1  ;
char id2  ;
char r2  ;
char st2  ;
char nl2  ;
char m2  ;
char max2  ;
bool mode2  ;
char id3  ;
char r3  ;
char st3  ;
char nl3  ;
char m3  ;
char max3  ;
bool mode3  ;
void node1(void) 
{ 


  {
printf("POINT: 1\n");

  if (mode1) {
printf("POINT: 2\n");
printf("POINT: 3\n");

    if (r1 == 255) {
printf("POINT: 4\n");
      r1 = 2;
    }
    r1 = r1 + 1;
printf("POINT: 5\n");

    if (ep21) {
printf("POINT: 6\n");
      m1 = p21_old;
      p21_old = nomsg;
printf("POINT: 7\n");

      if ((int )m1 > (int )max1) {
printf("POINT: 8\n");
        max1 = m1;
      }
    }
printf("POINT: 9\n");

    if (ep31) {
printf("POINT: 10\n");
      m1 = p31_old;
      p31_old = nomsg;
printf("POINT: 11\n");

      if ((int )m1 > (int )max1) {
printf("POINT: 12\n");
        max1 = m1;
      }
    }
printf("POINT: 13\n");

    if ((int )r1 == 2) {
printf("POINT: 14\n");
printf("POINT: 15\n");

      if ((int )max1 == (int )id1) {
printf("POINT: 16\n");
        st1 = (char)1;
      } else {
printf("POINT: 18\n");
        nl1 = (char)1;
      }
    }
    mode1 = (bool)0;
  } else {
printf("POINT: 20\n");
printf("POINT: 21\n");

    if ((int )r1 < 1) {
printf("POINT: 22\n");
printf("POINT: 23\n");

      if (ep12) {
printf("POINT: 24\n");
        
        
printf("POINT: 25\n");

     if ((max1 != nomsg) && (p12_new == nomsg)){
printf("POINT: 26\n");
    p12_new = max1;
    }
    else{
    p12_new = p12_new;
    }
        
        
      }
printf("POINT: 27\n");

      if (ep13) {
printf("POINT: 28\n");

     
printf("POINT: 29\n");

     if ((max1 != nomsg) && (p13_new == nomsg)){
printf("POINT: 30\n");
    p13_new = max1;
    }
    else{
    p13_new = p13_new;
    }
    
     
      }
    }
    mode1 = (bool)1;
  }
  return;
}
}
void node2(void) 
{ 


  {
printf("POINT: 31\n");

  if (mode2) {
printf("POINT: 32\n");
printf("POINT: 33\n");

    if (r2 == 255) {
printf("POINT: 34\n");
      r2 = 2;
    }
    r2 = r2 + 1;
printf("POINT: 35\n");

    if (ep12) {
printf("POINT: 36\n");
      m2 = p12_old;
      p12_old = nomsg;
printf("POINT: 37\n");

      if ((int )m2 > (int )max2) {
printf("POINT: 38\n");
        max2 = m2;
      }
    }
printf("POINT: 39\n");

    if (ep32) {
printf("POINT: 40\n");
      m2 = p32_old;
      p32_old = nomsg;
printf("POINT: 41\n");

      if ((int )m2 > (int )max2) {
printf("POINT: 42\n");
        max2 = m2;
      }
    }
printf("POINT: 43\n");

    if ((int )r2 == 2) {
printf("POINT: 44\n");
printf("POINT: 45\n");

      if ((int )max2 == (int )id2) {
printf("POINT: 46\n");
        st2 = (char)1;
      } else {
printf("POINT: 48\n");
        nl2 = (char)1;
      }
    }
    mode2 = (bool)0;
  } else {
printf("POINT: 50\n");
printf("POINT: 51\n");

    if ((int )r2 < 2) {
printf("POINT: 52\n");
printf("POINT: 53\n");

      if (ep21) {
printf("POINT: 54\n");
        
printf("POINT: 55\n");

    if ((max2 != nomsg) && (p21_new == nomsg)){
printf("POINT: 56\n");
    p21_new = max2;
    }
    else{
    p21_new = p21_new;
    }
        
        
      }
printf("POINT: 57\n");

      if (ep23) {
printf("POINT: 58\n");
    
printf("POINT: 59\n");

    if ((max2 != nomsg) && (p23_new == nomsg)){
printf("POINT: 60\n");
    p23_new = max2;
    }
    else{
    p23_new = p23_new;
    }

   
      }
    }
    mode2 = (bool)1;
  }
  return;
}
}
void node3(void) 
{ 


  {
printf("POINT: 61\n");

  if (mode3) {
printf("POINT: 62\n");
printf("POINT: 63\n");

    if (r3 == 255) {
printf("POINT: 64\n");
      r3 = 2;
    }
    r3 = r3 + 1;
printf("POINT: 65\n");

    if (ep13) {
printf("POINT: 66\n");
      m3 = p13_old;
      p13_old = nomsg;
printf("POINT: 67\n");

      if ((int )m3 > (int )max3) {
printf("POINT: 68\n");
        max3 = m3;
      }
    }
printf("POINT: 69\n");

    if (ep23) {
printf("POINT: 70\n");
      m3 = p23_old;
      p23_old = nomsg;
printf("POINT: 71\n");

      if ((int )m3 > (int )max3) {
printf("POINT: 72\n");
        max3 = m3;
      }
    }
printf("POINT: 73\n");

    if ((int )r3 == 2) {
printf("POINT: 74\n");
printf("POINT: 75\n");

      if ((int )max3 == (int )id3) {
printf("POINT: 76\n");
        st3 = (char)1;
      } else {
printf("POINT: 78\n");
        nl3 = (char)1;
      }
    }
    mode3 = (bool)0;
  } else {
printf("POINT: 80\n");
printf("POINT: 81\n");

    if ((int )r3 < 2) {
printf("POINT: 82\n");
printf("POINT: 83\n");

      if (ep31) {
printf("POINT: 84\n");
        
printf("POINT: 85\n");

    if ((max3 != nomsg) && (p31_new == nomsg)){
printf("POINT: 86\n");
    p31_new = max3;
    }
    else{
    p31_new = p31_new;
    }
        
        
      }
printf("POINT: 87\n");

      if (ep32) {
printf("POINT: 88\n");
        
printf("POINT: 89\n");

    if ((max3 != nomsg) && (p32_new == nomsg)){
printf("POINT: 90\n");
    p32_new = max3;
    }
    else{
    p32_new = p32_new;
    }
        
      }
    }
    mode3 = (bool)1;
  }
  return;
}
}
void (*nodes[3])(void)  = {      & node1,      & node2,      & node3};
int init(void) 
{ 
  bool r121 ;
  bool r131 ;
  bool r211 ;
  bool r231 ;
  bool r311 ;
  bool r321 ;
  bool r122 ;
  int tmp ;
  bool r132 ;
  int tmp___0 ;
  bool r212 ;
  int tmp___1 ;
  bool r232 ;
  int tmp___2 ;
  bool r312 ;
  int tmp___3 ;
  bool r322 ;
  int tmp___4 ;
  int tmp___5 ;

  {
  r121 = ep12;
  r131 = ep13;
  r211 = ep21;
  r231 = ep23;
  r311 = ep31;
  r321 = ep32;
printf("POINT: 91\n");

  if (r121) {
printf("POINT: 92\n");
    tmp = 1;
printf("POINT: 93\n");

  } else if (r131) {
printf("POINT: 94\n");
printf("POINT: 95\n");

    if (ep32) {
printf("POINT: 96\n");
      tmp = 1;
    } else {
printf("POINT: 98\n");
      tmp = 0;
    }
  } else {
printf("POINT: 100\n");
    tmp = 0;
  }
  r122 = (bool )tmp;
printf("POINT: 101\n");

  if (r131) {
printf("POINT: 102\n");
    tmp___0 = 1;
printf("POINT: 103\n");

  } else if (r121) {
printf("POINT: 104\n");
printf("POINT: 105\n");

    if (ep23) {
printf("POINT: 106\n");
      tmp___0 = 1;
    } else {
printf("POINT: 108\n");
      tmp___0 = 0;
    }
  } else {
printf("POINT: 110\n");
    tmp___0 = 0;
  }
  r132 = (bool )tmp___0;
printf("POINT: 111\n");

  if (r211) {
printf("POINT: 112\n");
    tmp___1 = 1;
printf("POINT: 113\n");

  } else if (r231) {
printf("POINT: 114\n");
printf("POINT: 115\n");

    if (ep31) {
printf("POINT: 116\n");
      tmp___1 = 1;
    } else {
printf("POINT: 118\n");
      tmp___1 = 0;
    }
  } else {
printf("POINT: 120\n");
    tmp___1 = 0;
  }
  r212 = (bool )tmp___1;
printf("POINT: 121\n");

  if (r231) {
printf("POINT: 122\n");
    tmp___2 = 1;
printf("POINT: 123\n");

  } else if (r211) {
printf("POINT: 124\n");
printf("POINT: 125\n");

    if (ep13) {
printf("POINT: 126\n");
      tmp___2 = 1;
    } else {
printf("POINT: 128\n");
      tmp___2 = 0;
    }
  } else {
printf("POINT: 130\n");
    tmp___2 = 0;
  }
  r232 = (bool )tmp___2;
printf("POINT: 131\n");

  if (r311) {
printf("POINT: 132\n");
    tmp___3 = 1;
printf("POINT: 133\n");

  } else if (r321) {
printf("POINT: 134\n");
printf("POINT: 135\n");

    if (ep21) {
printf("POINT: 136\n");
      tmp___3 = 1;
    } else {
printf("POINT: 138\n");
      tmp___3 = 0;
    }
  } else {
printf("POINT: 140\n");
    tmp___3 = 0;
  }
  r312 = (bool )tmp___3;
printf("POINT: 141\n");

  if (r321) {
printf("POINT: 142\n");
    tmp___4 = 1;
printf("POINT: 143\n");

  } else if (r311) {
printf("POINT: 144\n");
printf("POINT: 145\n");

    if (ep12) {
printf("POINT: 146\n");
      tmp___4 = 1;
    } else {
printf("POINT: 148\n");
      tmp___4 = 0;
    }
  } else {
printf("POINT: 150\n");
    tmp___4 = 0;
  }
  r322 = (bool )tmp___4;
printf("POINT: 151\n");

  if ((int )id1 != (int )id2) {
printf("POINT: 152\n");
printf("POINT: 153\n");

    if ((int )id1 != (int )id3) {
printf("POINT: 154\n");
printf("POINT: 155\n");

      if ((int )id2 != (int )id3) {
printf("POINT: 156\n");
printf("POINT: 157\n");

        if ((int )id1 >= 0) {
printf("POINT: 158\n");
printf("POINT: 159\n");

          if ((int )id2 >= 0) {
printf("POINT: 160\n");
printf("POINT: 161\n");

            if ((int )id3 >= 0) {
printf("POINT: 162\n");
printf("POINT: 163\n");

              if ((int )r1 == 0) {
printf("POINT: 164\n");
printf("POINT: 165\n");

                if ((int )r2 == 0) {
printf("POINT: 166\n");
printf("POINT: 167\n");

                  if ((int )r3 == 0) {
printf("POINT: 168\n");
printf("POINT: 169\n");

                    if (r122) {
printf("POINT: 170\n");
printf("POINT: 171\n");

                      if (r132) {
printf("POINT: 172\n");
printf("POINT: 173\n");

                        if (r212) {
printf("POINT: 174\n");
printf("POINT: 175\n");

                          if (r232) {
printf("POINT: 176\n");
printf("POINT: 177\n");

                            if (r312) {
printf("POINT: 178\n");
printf("POINT: 179\n");

                              if (r322) {
printf("POINT: 180\n");
printf("POINT: 181\n");

                                if ((int )max1 == (int )id1) {
printf("POINT: 182\n");
printf("POINT: 183\n");

                                  if ((int )max2 == (int )id2) {
printf("POINT: 184\n");
printf("POINT: 185\n");

                                    if ((int )max3 == (int )id3) {
printf("POINT: 186\n");
printf("POINT: 187\n");

                                      if ((int )st1 == 0) {
printf("POINT: 188\n");
printf("POINT: 189\n");

                                        if ((int )st2 == 0) {
printf("POINT: 190\n");
printf("POINT: 191\n");

                                          if ((int )st3 == 0) {
printf("POINT: 192\n");
printf("POINT: 193\n");

                                            if ((int )nl1 == 0) {
printf("POINT: 194\n");
printf("POINT: 195\n");

                                              if ((int )nl2 == 0) {
printf("POINT: 196\n");
printf("POINT: 197\n");

                                                if ((int )nl3 == 0) {
printf("POINT: 198\n");
printf("POINT: 199\n");

                                                  if ((int )mode1 == 0) {
printf("POINT: 200\n");
printf("POINT: 201\n");

                                                    if ((int )mode2 == 0) {
printf("POINT: 202\n");
printf("POINT: 203\n");

                                                      if ((int )mode3 == 0) {
printf("POINT: 204\n");
                                                        tmp___5 = 1;
                                                      } else {
printf("POINT: 206\n");
                                                        tmp___5 = 0;
                                                      }
                                                    } else {
printf("POINT: 208\n");
                                                      tmp___5 = 0;
                                                    }
                                                  } else {
printf("POINT: 210\n");
                                                    tmp___5 = 0;
                                                  }
                                                } else {
printf("POINT: 212\n");
                                                  tmp___5 = 0;
                                                }
                                              } else {
printf("POINT: 214\n");
                                                tmp___5 = 0;
                                              }
                                            } else {
printf("POINT: 216\n");
                                              tmp___5 = 0;
                                            }
                                          } else {
printf("POINT: 218\n");
                                            tmp___5 = 0;
                                          }
                                        } else {
printf("POINT: 220\n");
                                          tmp___5 = 0;
                                        }
                                      } else {
printf("POINT: 222\n");
                                        tmp___5 = 0;
                                      }
                                    } else {
printf("POINT: 224\n");
                                      tmp___5 = 0;
                                    }
                                  } else {
printf("POINT: 226\n");
                                    tmp___5 = 0;
                                  }
                                } else {
printf("POINT: 228\n");
                                  tmp___5 = 0;
                                }
                              } else {
printf("POINT: 230\n");
                                tmp___5 = 0;
                              }
                            } else {
printf("POINT: 232\n");
                              tmp___5 = 0;
                            }
                          } else {
printf("POINT: 234\n");
                            tmp___5 = 0;
                          }
                        } else {
printf("POINT: 236\n");
                          tmp___5 = 0;
                        }
                      } else {
printf("POINT: 238\n");
                        tmp___5 = 0;
                      }
                    } else {
printf("POINT: 240\n");
                      tmp___5 = 0;
                    }
                  } else {
printf("POINT: 242\n");
                    tmp___5 = 0;
                  }
                } else {
printf("POINT: 244\n");
                  tmp___5 = 0;
                }
              } else {
printf("POINT: 246\n");
                tmp___5 = 0;
              }
            } else {
printf("POINT: 248\n");
              tmp___5 = 0;
            }
          } else {
printf("POINT: 250\n");
            tmp___5 = 0;
          }
        } else {
printf("POINT: 252\n");
          tmp___5 = 0;
        }
      } else {
printf("POINT: 254\n");
        tmp___5 = 0;
      }
    } else {
printf("POINT: 256\n");
      tmp___5 = 0;
    }
  } else {
printf("POINT: 258\n");
    tmp___5 = 0;
  }
  return (tmp___5);
}
}
int check(void) 
{ 
  int tmp ;

  {
printf("POINT: 259\n");

  if (((int )st1 + (int )st2) + (int )st3 <= 1) {
printf("POINT: 260\n");
printf("POINT: 261\n");

    if ((int )st1 + (int )nl1 <= 1) {
printf("POINT: 262\n");
printf("POINT: 263\n");

      if ((int )st2 + (int )nl2 <= 1) {
printf("POINT: 264\n");
printf("POINT: 265\n");

        if ((int )st3 + (int )nl3 <= 1) {
printf("POINT: 266\n");
printf("POINT: 267\n");

          if ((int )r1 >= 2) {
printf("POINT: 268\n");
            goto _L___1;
printf("POINT: 269\n");

          } else if (((int )st1 + (int )st2) + (int )st3 == 0) {
printf("POINT: 270\n");
            _L___1: /* CIL Label */ 
printf("POINT: 271\n");

            if ((int )r1 < 2) {
printf("POINT: 272\n");
              goto _L___0;
printf("POINT: 273\n");

            } else if (((int )st1 + (int )st2) + (int )st3 == 1) {
printf("POINT: 274\n");
              _L___0: /* CIL Label */ 
printf("POINT: 275\n");

              if ((int )r1 >= 2) {
printf("POINT: 276\n");
                goto _L;
printf("POINT: 277\n");

              } else if (((int )nl1 + (int )nl2) + (int )nl3 == 0) {
printf("POINT: 278\n");
                _L: /* CIL Label */ 
printf("POINT: 279\n");

                if ((int )r1 < 2) {
printf("POINT: 280\n");
                  tmp = 1;
printf("POINT: 281\n");

                } else if (((int )nl1 + (int )nl2) + (int )nl3 == 2) {
printf("POINT: 282\n");
                  tmp = 1;
                } else {
printf("POINT: 284\n");
                  tmp = 0;
                }
              } else {
printf("POINT: 286\n");
                tmp = 0;
              }
            } else {
printf("POINT: 288\n");
              tmp = 0;
            }
          } else {
printf("POINT: 290\n");
            tmp = 0;
          }
        } else {
printf("POINT: 292\n");
          tmp = 0;
        }
      } else {
printf("POINT: 294\n");
        tmp = 0;
      }
    } else {
printf("POINT: 296\n");
      tmp = 0;
    }
  } else {
printf("POINT: 298\n");
    tmp = 0;
  }
  return (tmp);
}
}


int main(void) 
{ 
  int c1 ;
  int i2 ;
  kappa = 0;
  {
  c1 = 0;
  
  
  scanf("%", &ep12);
  scanf("%", &ep13);
  
  scanf("%", &ep21);
  scanf("%", &ep23);
  
  scanf("%", &ep31);
  scanf("%", &ep32);
  
  scanf("%c", &id1);
  scanf("%c", &r1);
  scanf("%c", &st1);
  scanf("%c", &nl1);
  scanf("%c", &m1);
  scanf("%c", &max1);
  scanf("%", &mode1);
  
  scanf("%c", &id2);
  scanf("%c", &r2);
  scanf("%c", &st2);
  scanf("%c", &nl2);
  scanf("%c", &m2);
  scanf("%c", &max2);
  scanf("%", &mode2);
  
  scanf("%c", &id3);
  scanf("%c", &r3);
  scanf("%c", &st3);
  scanf("%c", &nl3);
  scanf("%c", &m3);
  scanf("%c", &max3);
  scanf("%", &mode3);
  
  
  
  
  i2 = init();

  p12_old = nomsg;
  p12_new = nomsg;
  p13_old = nomsg;
  p13_new = nomsg;
  p21_old = nomsg;
  p21_new = nomsg;
  p23_old = nomsg;
  p23_new = nomsg;
  p31_old = nomsg;
  p31_new = nomsg;
  p32_old = nomsg;
  p32_new = nomsg;
  i2 = 0;
printf("POINT: 299\n");

      while (i2 < 1) {
printf("POINT: 300\n");
    {
    node1();
    node2();
    node3();
    p12_old = p12_new;
    p12_new = nomsg;
    p13_old = p13_new;
    p13_new = nomsg;
    p21_old = p21_new;
    p21_new = nomsg;
    p23_old = p23_new;
    p23_new = nomsg;
    p31_old = p31_new;
    p31_new = nomsg;
    p32_old = p32_new;
    p32_new = nomsg;
    c1 = check();
    i2++;
    }
  }
}

return 0;
}
