/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */
#include<stdio.h>
extern int printf(char const   * __restrict  __format  , ...) ;
int kappa  ;
int input  ;
int output  ;
int inputs[10]  = 
  {      10,      6,      1,      8, 
        2,      5,      7,      9, 
        4,      3};
void calculate_output(int input___0 ) ;
void calculate_outputm1(int input___0 ) ;
int a49  =    10;
int a180  =    316;
int a65[6]  = {      25,      26,      27,      28, 
        29,      30};
int a198[6]  = {      31,      32,      33,      34, 
        35,      36};
int a77[6]  = {      37,      38,      39,      40, 
        41,      42};
int *a140  =    a198;
int a172[8]  = 
  {      2,      3,      4,      5, 
        6,      7,      8,      9};
int a105  =    34;
int cf  =    1;
int a134[8]  = 
  {      2,      3,      4,      5, 
        6,      7,      8,      9};
int a160  =    4;
int a87  =    33;
int a139  =    124;
int a170  =    3;
int a90[6]  = {      28,      29,      30,      31, 
        32,      33};
int a113[6]  = {      34,      35,      36,      37, 
        38,      39};
int a82[6]  = {      40,      41,      42,      43, 
        44,      45};
int *a3  =    a82;
int a114  =    8;
int a120  =    35;
int a177  =    34;
int a72  =    17;
int a185[6]  = {      34,      35,      36,      37, 
        38,      39};
int a110[6]  = {      40,      41,      42,      43, 
        44,      45};
int a4[6]  = {      46,      47,      48,      49, 
        50,      51};
int *a0  =    a4;
int a16  =    28;
int a121  =    32;
int a147  =    35;
void calculate_outputm1(int input___0 ) 
{ 


  {
  return;
}
}
void calculate_output(int input___0 ) 
{ 


  {
  cf = 1;
  if ((a105 == 33 && ((a105 == 33 && (cf == 1 && a180 <= 64)) && a49 == 8)) && ((33 == *(a3 + 5) && a105 == 33) && a139 <= -26)) {
    if (((((cf == 1 && 29 == *(a140 + 4)) && a49 == 8) && 33 == *(a3 + 5)) && a139 <= -26) && ((33 == *(a3 + 5) && a139 <= -26) && 33 == *(a3 + 5))) {
      calculate_outputm1(input___0);
    }
  }
  printf((char const   * __restrict  )"%d \n", a160);
  printf((char const   * __restrict  )"%d \n", a105);
  printf((char const   * __restrict  )"%d \n", a139);
  printf((char const   * __restrict  )"%d \n", cf);
  printf((char const   * __restrict  )"%d \n", a105);
  printf((char const   * __restrict  )"%d \n", a49);
  printf((char const   * __restrict  )"%d \n", input___0);
  return;
}
}
extern int ( /* missing proto */  nondet_int)() ;
extern int ( /* missing proto */  __CPROVER_input)() ;
int main(void) 
{ 
  int symb ;
  int FLAG ;

  {
  kappa = 0;
  FLAG = 0;
  while (FLAG < 5) {
    int symb = nondet_int();
    __CPROVER_input("symb", symb);
    if (((((((((symb != 10 && symb != 6) && symb != 1) && symb != 8) && symb != 2) && symb != 5) && symb != 7) && symb != 9) && symb != 4) && symb != 3) {
      printf((char const   * __restrict  )"%d \n",-2);
    }
    calculate_output(symb);
    FLAG ++;
  }
  return (0);
}
}
